module.exports = {
  url: "https://peterkaizer.com",
  author: "Peter Kaizer",
  tagline: "Product Designer",
  description: "Product design portfolio — case studies in UX, interaction design, and design systems.",
  defaultOgImage: "/assets/images/pdk-about-photo.jpg",
  mapboxToken: process.env.MAPBOX_TOKEN || "",
  location: "Baltimore",
  email: "peter@peterkaizer.com",
  social: [
    { label: "Instagram", url: "https://instagram.com/pdkaizer", icon: "fa-brands fa-instagram" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/pdkaizer/", icon: "fa-brands fa-linkedin-in" },
    { label: "Dribbble", url: "https://dribbble.com/pdkaizer", icon: "fa-brands fa-dribbble" },
    { label: "Bluesky", url: "https://bsky.app/profile/pdkaizer.bsky.social/", icon: "fa-brands fa-bluesky" },
    { label: "Mastodon", url: "https://toad.social/@pdkaizer", icon: "fa-brands fa-mastodon" },
    { label: "GitHium", url: "https://github.com/pdkaizer", icon: "fa-brands fa-github" },
  ],
  nav: [
    { label: "Work", url: "/work/" },
    { label: "Photos", url: "/photos/" },
    { label: "Thoughts", url: "/thoughts/" },
    { label: "Articles", url: "/articles/" },
    { label: "Links", url: "/links/" },
    { label: "Listening", url: "/listening/" },
    { label: "About", url: "/about/" },
    { label: "Gear", url: "/gear/" },
    { label: "Contact", url: "/contact/" },
    { label: "Recommended Books", url: "https://books.peterkaizer.com" },
  ],
};
